In [1]:
## Import required modules

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
## Read files

population = pd.read_csv('../../data/07_CENSUS_MICRODATA/07_04_CNPV2018_5PER_A2_11.csv', converters={'COD_ENCUESTAS':str})
mgn = pd.read_csv('../../data/07_CENSUS_MICRODATA/07_05_CNPV2018_MGN_A2_11.csv', converters={'U_DPTO':str, 'U_MPIO':str, 'UA_CLASE':str, 'UA1_LOCALIDAD':str,
                                                'U_SECT_RUR':str, 'U_SECC_RUR':str, 'U_SECT_URB':str,'U_SECC_URB':str, 'U_MZA':str,
                                                'COD_ENCUESTAS':str,'U_EDIFICA':str, 'U_VIVIENDA':str})
dwelling = pd.read_csv('../../data/07_CENSUS_MICRODATA/07_01_CNPV2018_1VIV_A2_11.csv', converters ={'COD_ENCUESTAS':str})

In [3]:
##Concatenate sector cde in mgn, 
mgn['cod_mzn'] = (mgn['U_DPTO']+mgn['U_MPIO']+mgn['UA_CLASE']+mgn['UA1_LOCALIDAD']+mgn['U_SECT_RUR']+mgn['U_SECC_RUR']+
                    mgn['U_SECT_URB']+mgn['U_SECC_URB']+mgn['U_MZA'])
mgn

,U_DPTO,U_MPIO,UA_CLASE,UA1_LOCALIDAD,U_SECT_RUR,U_SECC_RUR,UA2_CPOB,U_SECT_URB,U_SECC_URB,U_MZA,U_EDIFICA,COD_ENCUESTAS,U_VIVIENDA,cod_mzn
0,11,001,1,00,000,00,0,0000,00,00,1,7119768,1,110011000000000000000
1,11,001,1,00,000,00,0,0000,00,00,1,750001936,1,110011000000000000000
2,11,001,1,00,000,00,0,0000,00,00,1,950001972,1,110011000000000000000
3,11,001,1,00,000,00,0,0000,00,00,1,950002492,1,110011000000000000000
4,11,001,1,00,000,00,0,0000,00,00,2,750000128,1,110011000000000000000
5,11,001,1,00,000,00,0,0000,00,00,2,750000129,2,110011000000000000000
6,11,001,1,00,000,00,0,0000,00,00,2,750000145,1,110011000000000000000
7,11,001,1,00,000,00,0,0000,00,00,2,750000163,1,110011000000000000000
8,11,001,1,00,000,00,0,0000,00,00,2,750000367,1,110011000000000000000
9,11,001,1,00,000,00,0,0000,00,00,2,750000371,15,110011000000000000000
10,11,001,1,00,000,00,0,0000,00,00,2,750000382,1,110011000000000000000
11,11,001,1,00,000,00,0,0000,00,00,2,750000432,4,110011000000000000000
12,11,001,1,00,000,00,0,0000,00,00,2,750000471,2,110011000000000000000
13,11,001,1,00,000,00,0,0000,00,00,2,750001254,1,110011000000000000000
14,11,001,1,00,000,00,0,0000,00,00,2,750001307,1,110011000000000000000
15,11,001,1,00,000,00,0,0000,00,00,2,750001320,2,110011000000000000000
16,11,001,1,00,000,00,0,0000,00,00,2,750001321,1,110011000000000000000
17,11,001,1,00,000,00,0,0000,00,00,2,750001363,1,110011000000000000000
18,11,001,1,00,000,00,0,0000,00,00,2,750001422,3,110011000000000000000
19,11,001,1,00,000,00,0,0000,00,00,2,750001484,3,110011000000000000000
20,11,001,1,00,000,00,0,0000,00,00,2,750001485,1,110011000000000000000
21,11,001,1,00,000,00,0,0000,00,00,2,750001560,8,110011000000000000000
22,11,001,1,00,000,00,0,0000,00,00,2,750001598,1,110011000000000000000
23,11,001,1,00,000,00,0,0000,00,00,2,750001606,2,110011000000000000000
24,11,001,1,00,000,00,0,0000,00,00,2,750001627,1,110011000000000000000
25,11,001,1,00,000,00,0,0000,00,00,2,750001629,3,110011000000000000000
26,11,001,1,00,000,00,0,0000,00,00,2,750001630,2,110011000000000000000
27,11,001,1,00,000,00,0,0000,00,00,2,750001635,1,110011000000000000000
28,11,001,1,00,000,00,0,0000,00,00,2,750001787,1,110011000000000000000
29,11,001,1,00,000,00,0,0000,00,00,2,750001842,2,110011000000000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2524397,11,001,4,00,011,00,0,0000,00,00,2,16630691,1,110014000110000000000
2524398,11,001,4,00,011,00,0,0000,00,00,2,16630718,1,110014000110000000000
2524399,11,001,4,00,011,00,0,0000,00,00,2,16630834,1,110014000110000000000
2524400,11,001,4,00,011,00,0,0000,00,00,2,16630936,1,110014000110000000000
2524401,11,001,4,00,011,00,0,0000,00,00,2,16631122,1,110014000110000000000
2524402,11,001,4,00,011,00,0,0000,00,00,2,16631177,1,110014000110000000000
2524403,11,001,4,00,011,00,0,0000,00,00,2,900372874,1,110014000110000000000
2524404,11,001,4,00,011,00,0,0000,00,00,2,900422841,1,110014000110000000000
2524405,11,001,4,00,011,00,0,0000,00,00,2,900459668,1,110014000110000000000
2524406,11,001,4,00,011,00,0,0000,00,00,2,900463624,1,110014000110000000000
2524407,11,001,4,00,011,00,0,0000,00,00,2,900494957,1,110014000110000000000
2524408,11,001,4,00,011,00,0,0000,00,00,2,900674804,1,110014000110000000000
2524409,11,001,4,00,011,00,0,0000,00,00,2,900927004,1,110014000110000000000
2524410,11,001,4,00,011,00,0,0000,00,00,2,901348678,1,110014000110000000000
2524411,11,001,4,00,011,00,0,0000,00,00,3,16631119,1,110014000110000000000
2524412,11,001,4,00,011,00,0,0000,00,00,3,900454166,1,110014000110000000000
2524413,11,001,4,00,011,00,0,0000,00,00,3,900570247,1,110014000110000000000
2524414,11,001,4,00,011,00,0,0000,00,00,3,900679862,1,110014000110000000000
2524415,11,001,4,00,011,00,0,0000,00,00,3,901235826,1,110014000110000000000
2524416,11,001,4,00,011,00,0,0000,00,00,3,901407629,1,110014000110000000000
2524417,11,001,4,00,011,00,0,0000,00,00,3,901461507,1,110014000110000000000
2524418,11,001,4,00,011,00,0,0000,00,00,4,16631153,1,110014000110000000000
2524419,11,001,4,00,011,00,0,0000,00,00,4,900781985,1,110014000110000000000
2524420,11,001,4,00,011,00,0,0000,00,00,4,901422323,1,110014000110000000000
2524421,11,001,4,00,011,00,0,0000,00,00,4,902175229,1,110014000110000000000
2524422,11,001,4,00,011,00,0,0000,00,00,5,901045319,1,110014000110000000000
2524423,11,001,4,00,011,00,0,0000,00,00,5,901444614,1,110014000110000000000
2524424,11,001,4,00,011,00,0,0000,00,00,6,901469342,1,110014000110000000000
2524425,11,001,4,00,011,00,0,0000,00,00,6,901508086,1,110014000110000000000
2524426,11,001,4,00,011,00,0,0000,00,00,7,901569988,1,110014000110000000000

In [4]:
## Grouping age categories like this
## G01 = Ages from 0 to 9, groups 1 and 2
## G02 = Ages from 10 to 19, groups 3 and 4
## G03 = Ages from 20 to 29, groups 5,6
## G04 = Ages from 30 to 64, groups 7,8,9,10,11,12,13
## G05 = Ages above 65, groups 14,15,16,17,18,19,20,21

population.loc[(population['P_EDADR'] <= 2),'age_group'] = "0 to 9"
population.loc[(population['P_EDADR'] >= 3),'age_group'] = "10 to 19"
population.loc[(population['P_EDADR'] >= 5),'age_group'] = "20 to 29"
population.loc[(population['P_EDADR'] >= 7),'age_group'] = "30 to 64"
population.loc[(population['P_EDADR'] >= 14),'age_group'] = "64 and more"




population

,TIPO_REG,U_DPTO,U_MPIO,UA_CLASE,U_EDIFICA,COD_ENCUESTAS,U_VIVIENDA,P_NROHOG,P_NRO_PER,P_SEXO,P_EDADR,P_PARENTESCOR,PA1_GRP_ETNIC,PA11_COD_ETNIA,PA12_CLAN,PA21_COD_VITSA,PA22_COD_KUMPA,PA_HABLA_LENG,PA1_ENTIENDE,PB_OTRAS_LENG,PB1_QOTRAS_LENG,PA_LUG_NAC,PA_VIVIA_5ANOS,PA_VIVIA_1ANO,P_ENFERMO,P_QUEHIZO_PPAL,PA_LO_ATENDIERON,PA1_CALIDAD_SERV,CONDICION_FISICA,P_ALFABETA,PA_ASISTENCIA,P_NIVEL_ANOSR,P_TRABAJO,P_EST_CIVIL,PA_HNV,PA1_THNV,PA2_HNVH,PA3_HNVM,PA_HNVS,PA1_THSV,PA2_HSVH,PA3_HSVM,PA_HFC,PA1_THFC,PA2_HFCH,PA3_HFCM,PA_UHNV,PA1_MES_UHNV,PA2_ANO_UHNV,age_group
0,5,11,1,1,4,60400,1,1.0,1,1,3,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,1.0,4.0,NaN,NaN,2.0,1.0,1.0,2.0,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
1,5,11,1,1,4,60400,1,1.0,2,2,10,2.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,1.0,4.0,NaN,NaN,2.0,1.0,2.0,8.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,3.0,2007.0,30 to 64
2,5,11,1,1,4,60400,1,1.0,3,2,5,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,8.0,6.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
3,5,11,1,1,4,60400,1,1.0,4,1,11,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
4,5,11,1,1,8,60404,1,1.0,1,2,12,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,3.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
5,5,11,1,1,8,60404,1,1.0,2,2,16,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,4.0,7.0,6.0,1.0,4.0,2.0,2.0,1.0,4.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,4.0,1970.0,64 and more
6,5,11,1,1,19,60408,1,1.0,1,2,12,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
7,5,11,1,1,19,60408,1,1.0,2,2,17,4.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,2.0,5.0,5.0,6.0,1.0,5.0,0.0,5.0,1.0,4.0,0.0,4.0,1.0,4.0,0.0,4.0,1.0,3.0,1964.0,64 and more
8,5,11,1,1,20,60409,1,1.0,1,2,10,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,9.0,2008.0,30 to 64
9,5,11,1,1,20,60409,1,1.0,2,1,11,2.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,9.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
10,5,11,1,1,20,60409,1,1.0,3,1,3,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,3.0,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
11,5,11,1,1,20,60409,1,1.0,4,2,2,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 to 9
12,5,11,1,1,21,60410,1,1.0,1,1,10,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,10.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
13,5,11,1,1,21,60410,1,1.0,2,1,3,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,3.0,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
14,5,11,1,1,22,60413,1,1.0,1,2,15,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,5.0,6.0,1.0,3.0,3.0,0.0,1.0,3.0,3.0,0.0,2.0,NaN,NaN,NaN,1.0,3.0,1968.0,64 and more
15,5,11,1,1,22,60413,1,1.0,2,1,11,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
16,5,11,1,1,22,60413,1,1.0,3,1,11,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,4.0,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
17,5,11,1,1,7,60416,1,1.0,1,2,16,2.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,7.0,2.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,10.0,1974.0,64 and more
18,5,11,1,1,7,60416,1,1.0,2,1,16,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64 and more
19,5,11,1,1,7,60416,1,1.0,3,2,9,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
20,5,11,1,1,6,60419,1,1.0,1,2,7,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
21,5,11,1,1,6,60419,1,1.0,2,1,14,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64 and more
22,5,11,1,1,6,60419,1,1.0,3,2,13,2.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,5.0,2.0,1.0,99.0,99.0,99.0,1.0,99.0,99.0,99.0,1.0,99.0,99.0,99.0,9.0,NaN,NaN,30 to 64
23,5,11,1,1,5,60420,1,1.0,1,2,14,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,5.0,6.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,NaN,NaN,NaN,1.0,10.0,1995.0,64 and more
24,5,11,1,1,5,60420,1,1.0,2,2,5,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,8.0,6.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
25,5,11,1,1,4,60422,1,1.0,1,1,9,4.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,9.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
26,5,11,1,1,4,60422,1,1.0,2,2,10,4.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,8.0,3.0,7.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,10.0,1996.0,30 to 64
27,5,11,1,1,4,60422,1,1.0,3,2,15,4.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,5.0,6.0,1.0,6.0,3.0,3.0,1.0,5.0,2.0,3.0,1.0,1.0,0.0,1.0,1.0,12.0,1973.0,64 and more
28,5,11,1,1,4,60422,1,1.0,4,2,11,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
29,5,11,1,1,4,60422,1,1.0,5,1,5,4.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,7.0,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7181439,5,11,1,4,2,902426134,1,1.0,2,1,5,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,9.0,9.0,9.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,1.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181440,5,11,1,4,2,902426134,1,1.0,3,1,4,4.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,9.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,4.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181441,5,11,1,4,3,902426281,1,1.0,1,1,15,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,8.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64 and more
7181442,5,11,1,4,3,902426281,1,1.0,2,2,11,2.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,8.0,1.0,2.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
7181443,5,11,1,4,3,902426526,1,1.0,1,1,12,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,5.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
7181444,5,11,1,4,3,902426526,1,1.0,2,2,10,2.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,7.0,1.0,1.0,4.0,3.0,1.0,1.0,4.0,3.0,1.0,9.0,NaN,NaN,NaN,1.0,10.0,2014.0,30 to 64
7181445,5,11,1,4,3,902426526,1,1.0,3,1,6,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,5.0,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181446,5,11,1,4,3,902426526,1,1.0,4,2,5,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,5.0,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181447,5,11,1,4,3,902426526,1,1.0,5,1,5,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,5.0,1.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181448,5,11,1,4,3,902426526,1,1.0,6,1,1,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,2.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 to 9
7181449,5,11,1,4,1,902426612,3,1.0,1,1,7,1.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4.0,4.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,8.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
7181450,5,11,1,4,3,902426614,1,1.0,1,1,5,1.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,8.0,9.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181451,5,11,1,4,3,902426614,1,1.0,2,2,12,4.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,8.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,9.0,NaN,NaN,NaN,1.0,8.0,1996.0,30 to 64
7181452,5,11,1,4,4,902427296,1,1.0,1,1,13,1.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
7181453,5,11,1,4,4,902427296,1,1.0,2,2,9,2.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,7.0,1.0,1.0,4.0,0.0,4.0,1.0,4.0,0.0,4.0,9.0,NaN,NaN,NaN,1.0,9.0,2004.0,30 to 64
7181454,5,11,1,4,4,902427296,1,1.0,3,2,5,3.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,8.0,0.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181455,5,11,1,4,4,902427296,1,1.0,4,2,4,3.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,4.0,0.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181456,5,11,1,4,4,902427296,1,1.0,5,2,4,3.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,4.0,0.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181457,5,11,1,4,4,902427296,1,1.0,6,2,3,3.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,3.0,0.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181458,5,11,1,4,2,902428795,1,1.0,1,1,12,1.0,1,999.0,NaN,NaN,NaN,9.0,NaN,9.0,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 64
7181459,5,11,1,4,2,902428795,1,1.0,2,2,11,2.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,99.0,7.0,2.0,1.0,6.0,2.0,4.0,1.0,6.0,2.0,4.0,9.0,NaN,NaN,NaN,9.0,NaN,NaN,30 to 64
7181460,5,11,1,4,2,902428795,1,1.0,3,1,5,3.0,1,999.0,NaN,NaN,NaN,9.0,NaN,9.0,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,5.0,3.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181461,5,11,1,4,2,902428795,1,1.0,4,1,4,3.0,1,999.0,NaN,NaN,NaN,9.0,NaN,9.0,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,4.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181462,5,11,1,4,2,902428795,1,1.0,5,2,4,3.0,1,999.0,NaN,NaN,NaN,2.0,9.0,9.0,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,5.0,6.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181463,5,11,1,4,2,902428795,1,1.0,6,1,3,3.0,1,999.0,NaN,NaN,NaN,9.0,NaN,9.0,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,3.0,6.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 to 19
7181464,5,11,1,4,2,902428795,1,1.0,7,1,6,3.0,1,999.0,NaN,NaN,NaN,9.0,NaN,9.0,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,5.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181465,5,11,1,4,21,902430274,1,1.0,1,2,10,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,2.0,5.0,7.0,4.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,9.0,NaN,NaN,NaN,1.0,1.0,1996.0,30 to 64
7181466,5,11,1,4,23,902438623,1,1.0,1,1,5,1.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,4.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29
7181467,5,11,1,4,23,902438623,1,1.0,2,2,1,3.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,2.0,9.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 to 9
7181468,5,11,1,4,23,902438623,1,1.0,3,2,6,4.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,7.0,2.0,7.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20 to 29

In [5]:
## Population per survey and sex

pop_sex = pd.pivot_table(population, values=['U_VIVIENDA'], index=['COD_ENCUESTAS','P_EDADR'], columns=['P_SEXO'], aggfunc='count', fill_value =0)

pop_sex

                      U_VIVIENDA
P_SEXO                         1  2
COD_ENCUESTAS P_EDADR
1000000       6                1  0
1000001       2                1  0
              4                0  1
              9                0  1
1000002       14               0  1
              16               0  1
1000003       13               0  1
              17               0  1
1000004       3                1  0
              9                0  1
1000005       3                1  0
              5                1  0
              9                0  1
1000006       1                1  0
              6                1  0
              7                1  0
              11               1  1
              12               0  1
              16               0  1
1000007       4                1  0
              5                2  1
              9                0  1
              10               1  0
1000008       2                1  0
              6                0  1
              8                1  0
              12               1  0
1000009       2                1  0
              3                0  1
              5                0  1
...                          ... ..
999990        2                1  0
              6                1  1
999991        1                1  0
              2                1  0
              6                0  1
              10               1  0
999992        11               0  1
999993        12               1  0
999994        16               0  1
9999946       5                1  0
              7                2  0
              10               1  0
999995        7                1  0
999996        5                1  0
              6                0  1
              10               1  0
              11               0  1
              18               0  1
              19               1  0
999997        7                1  0
9999978       4                2  0
              5                1  0
              9                0  2
              13               1  1
              14               1  0
999998        5                0  1
              10               1  0
              11               2  1
              16               0  1
999999        5                1  0

[6187434 rows x 2 columns]

In [6]:
pop_sex_flat = pd.DataFrame(pop_sex.to_records())
## Replace when you have the dictionary
pop_sex_flat.columns = ['COD_ENCUESTAS','AGE_GROUP','male','female']
pop_sex_flat

        COD_ENCUESTAS  AGE_GROUP  male  female
0             1000000          6     1       0
1             1000001          2     1       0
2             1000001          4     0       1
3             1000001          9     0       1
4             1000002         14     0       1
5             1000002         16     0       1
6             1000003         13     0       1
7             1000003         17     0       1
8             1000004          3     1       0
9             1000004          9     0       1
10            1000005          3     1       0
11            1000005          5     1       0
12            1000005          9     0       1
13            1000006          1     1       0
14            1000006          6     1       0
15            1000006          7     1       0
16            1000006         11     1       1
17            1000006         12     0       1
18            1000006         16     0       1
19            1000007          4     1       0
20            1000007          5     2       1
21            1000007          9     0       1
22            1000007         10     1       0
23            1000008          2     1       0
24            1000008          6     0       1
25            1000008          8     1       0
26            1000008         12     1       0
27            1000009          2     1       0
28            1000009          3     0       1
29            1000009          5     0       1
...               ...        ...   ...     ...
6187404        999990          2     1       0
6187405        999990          6     1       1
6187406        999991          1     1       0
6187407        999991          2     1       0
6187408        999991          6     0       1
6187409        999991         10     1       0
6187410        999992         11     0       1
6187411        999993         12     1       0
6187412        999994         16     0       1
6187413       9999946          5     1       0
6187414       9999946          7     2       0
6187415       9999946         10     1       0
6187416        999995          7     1       0
6187417        999996          5     1       0
6187418        999996          6     0       1
6187419        999996         10     1       0
6187420        999996         11     0       1
6187421        999996         18     0       1
6187422        999996         19     1       0
6187423        999997          7     1       0
6187424       9999978          4     2       0
6187425       9999978          5     1       0
6187426       9999978          9     0       2
6187427       9999978         13     1       1
6187428       9999978         14     1       0
6187429        999998          5     0       1
6187430        999998         10     1       0
6187431        999998         11     2       1
6187432        999998         16     0       1
6187433        999999          5     1       0

[6187434 rows x 4 columns]

In [7]:
## Reduce mgn and dwelling to the basics 

mgn_reduced=mgn[['COD_ENCUESTAS','cod_mzn']]
dwelling_reduced=dwelling[['COD_ENCUESTAS','VA1_ESTRATO']]

## Join population data to mgn, group by block and flat

pop_age_sex=pd.merge(pop_sex_flat,mgn_reduced, how = 'left', on='COD_ENCUESTAS')
pop_age_sex_strata=pd.merge(pop_age_sex, dwelling_reduced, how='left', on='COD_ENCUESTAS')

## Group by cod_block, age group and strata

pop_sex_categories = pop_age_sex_strata.groupby(['cod_mzn','VA1_ESTRATO'])['male','female'].agg('sum')
pop_sex_flat = pd.DataFrame(pop_sex_categories.to_records())


## Replace when you have the dictionary
pop_sex_flat['population']=pop_sex_flat['male']+pop_sex_flat['female']

pop_sex_flat

                     cod_mzn  VA1_ESTRATO  male  female  population
0      110011000000000000000          2.0     2       4           6
1      110011000000000000000          3.0     4       2           6
2      110011000000000000000          4.0     2       2           4
3      110011000000011010101          2.0     6       7          13
4      110011000000011010102          1.0     1       0           1
5      110011000000011010102          2.0   235     206         441
6      110011000000011010103          1.0     4       8          12
7      110011000000011010103          2.0   356     394         750
8      110011000000011010103          3.0     6       6          12
9      110011000000011010103          4.0     1       1           2
10     110011000000011010103          5.0     3       1           4
11     110011000000011010103          9.0     0       2           2
12     110011000000011010104          0.0     1       1           2
13     110011000000011010104          1.0     5       3           8
14     110011000000011010104          2.0  1055    1143        2198
15     110011000000011010104          3.0   136     154         290
16     110011000000011010104          4.0     2       0           2
17     110011000000011010105          2.0   117     105         222
18     110011000000011010105          3.0     0       2           2
19     110011000000011010106          1.0     3       6           9
20     110011000000011010106          2.0    96     100         196
21     110011000000011010106          3.0     0       4           4
22     110011000000011010107          1.0     9      17          26
23     110011000000011010107          2.0   114     136         250
24     110011000000011010107          3.0     1       0           1
25     110011000000011010108          1.0     5       6          11
26     110011000000011010108          2.0    54      56         110
27     110011000000011020101          2.0    79      79         158
28     110011000000011020101          3.0     3       5           8
29     110011000000011020102          2.0    25      28          53
...                      ...          ...   ...     ...         ...
76508  110014000050000000000          9.0    21      10          31
76509  110014000060000000000          0.0     1       3           4
76510  110014000060000000000          1.0   184     162         346
76511  110014000060000000000          2.0    25      25          50
76512  110014000060000000000          3.0     2       8          10
76513  110014000060000000000          4.0     3       0           3
76514  110014000060000000000          9.0     3       0           3
76515  110014000070000000000          1.0   183     171         354
76516  110014000070000000000          2.0    66      66         132
76517  110014000070000000000          3.0    15      13          28
76518  110014000070000000000          4.0     4       3           7
76519  110014000070000000000          9.0     5       1           6
76520  110014000080000000000          1.0     1       0           1
76521  110014000080000000000          2.0     2       1           3
76522  110014000080000000000          3.0     1       0           1
76523  110014000090000000000          1.0    95      85         180
76524  110014000090000000000          2.0    19      13          32
76525  110014000090000000000          3.0    17      13          30
76526  110014000090000000000          4.0     0       1           1
76527  110014000090000000000          9.0     2       3           5
76528  110014000100000000000          0.0     0       1           1
76529  110014000100000000000          1.0   178     150         328
76530  110014000100000000000          2.0    17      21          38
76531  110014000100000000000          3.0     9      10          19
76532  110014000100000000000          4.0     3       5           8
76533  110014000110000000000          1.0   101      78         179
76534  110014000110000000000          2.0    21      14          35
76535  110014000110000000000          3.0     7       3          10
76536  110014000110000000000          4.0     1       0           1
76537  110014000110000000000          6.0     1       1           2

[76538 rows x 5 columns]

In [8]:
## Population per block and strata

pop_strata=pd.pivot_table(pop_sex_flat, values=['population'], index=['cod_mzn'], columns=['VA1_ESTRATO'], aggfunc = 'sum', fill_value = 0)
pop_strata = pd.DataFrame(pop_strata.to_records())
pop_strata.columns = ['cod_mz','E00','E01','E02','E03','E04','E05','E06','E09']
pop_strata['max_population'] = pop_strata.max(axis=1)

pop_strata.loc[(pop_strata['E01'] == pop_strata['max_population']), 'main_strata'] = "E01"
pop_strata.loc[(pop_strata['E02'] == pop_strata['max_population']), 'main_strata'] = "E02"
pop_strata.loc[(pop_strata['E03'] == pop_strata['max_population']), 'main_strata'] = "E03"
pop_strata.loc[(pop_strata['E04'] == pop_strata['max_population']), 'main_strata'] = "E04"
pop_strata.loc[(pop_strata['E05'] == pop_strata['max_population']), 'main_strata'] = "E05"
pop_strata.loc[(pop_strata['E06'] == pop_strata['max_population']), 'main_strata'] = "E06"

pop_strata

,cod_mz,E00,E01,E02,E03,E04,E05,E06,E09,max_population,main_strata
0,110011000000000000000,0,0,6,6,4,0,0,0,6,E03
1,110011000000011010101,0,0,13,0,0,0,0,0,13,E02
2,110011000000011010102,0,1,441,0,0,0,0,0,441,E02
3,110011000000011010103,0,12,750,12,2,4,0,2,750,E02
4,110011000000011010104,2,8,2198,290,2,0,0,0,2198,E02
5,110011000000011010105,0,0,222,2,0,0,0,0,222,E02
6,110011000000011010106,0,9,196,4,0,0,0,0,196,E02
7,110011000000011010107,0,26,250,1,0,0,0,0,250,E02
8,110011000000011010108,0,11,110,0,0,0,0,0,110,E02
9,110011000000011020101,0,0,158,8,0,0,0,0,158,E02
10,110011000000011020102,0,0,53,4,0,0,0,0,53,E02
11,110011000000011020103,0,3,406,7,0,0,0,0,406,E02
12,110011000000011020104,0,0,99,0,0,0,0,0,99,E02
13,110011000000011020105,0,0,139,0,0,0,0,0,139,E02
14,110011000000011020107,0,4,130,1,3,0,0,0,130,E02
15,110011000000011020109,0,0,133,3,0,0,0,0,133,E02
16,110011000000011020110,0,0,452,5,0,0,0,0,452,E02
17,110011000000011020111,0,3,168,3,0,0,0,2,168,E02
18,110011000000011020113,0,0,116,0,0,0,0,0,116,E02
19,110011000000011020116,0,0,678,21,0,0,0,0,678,E02
20,110011000000011020118,0,0,148,1,0,0,0,0,148,E02
21,110011000000011020119,0,0,98,0,0,0,0,0,98,E02
22,110011000000011020120,0,1,720,60,2,0,0,2,720,E02
23,110011000000011020201,0,0,70,0,0,0,0,0,70,E02
24,110011000000011020202,0,0,187,0,0,0,0,0,187,E02
25,110011000000011020203,0,0,250,0,0,0,0,0,250,E02
26,110011000000011020204,0,3,229,0,0,0,0,0,229,E02
27,110011000000011020205,0,0,120,0,0,0,0,0,120,E02
28,110011000000011020206,0,0,121,0,0,0,0,0,121,E02
29,110011000000011020207,0,0,48,0,0,0,0,0,48,E02
...,...,...,...,...,...,...,...,...,...,...,...
38376,110011000000092220619,0,0,3,253,0,0,0,5,253,E03
38377,110011000000092220620,0,0,0,246,0,0,1,0,246,E03
38378,110011000000092220621,0,0,0,258,0,0,0,0,258,E03
38379,110011000000092220622,0,0,0,116,0,0,0,0,116,E03
38380,110011000000092220626,0,0,0,183,0,0,0,0,183,E03
38381,110011000000092220703,0,0,1,196,0,0,0,0,196,E03
38382,110011000000092220704,0,0,1,235,0,4,0,0,235,E03
38383,110011000000092220705,0,0,1,276,0,0,0,0,276,E03
38384,110011000000092220706,0,0,0,256,0,0,0,0,256,E03
38385,110011000000092220707,0,0,0,207,0,0,0,0,207,E03
38386,110011000000092220708,0,4,2,230,0,0,0,0,230,E03
38387,110011000000092220709,0,0,1,208,0,0,0,0,208,E03
38388,110011000000092220710,0,0,0,251,0,0,0,0,251,E03
38389,110011000000092220716,0,0,8,2717,0,6,0,0,2717,E03
38390,110011000000092220717,0,0,11,1262,0,0,0,0,1262,E03
38391,110011000000092220719,0,0,10,1449,0,0,0,0,1449,E03
38392,110011000000092220720,0,0,4,118,0,0,0,0,118,E03
38393,110011000000092220721,0,0,0,179,0,0,0,0,179,E03
38394,110011000000092220722,0,2,33,1992,0,0,0,0,1992,E03
38395,110014000010000000000,22,114,1075,150,94,196,508,15,1075,E02
38396,110014000020000000000,29,442,447,120,43,29,25,13,447,E02
38397,110014000030000000000,120,3077,919,72,12,0,7,8,3077,E01
38398,110014000040000000000,9,1124,1935,106,16,11,0,3,1935,E02
38399,110014000050000000000,12,829,829,149,39,24,21,31,829,E02
38400,110014000060000000000,4,346,50,10,3,0,0,3,346,E01
38401,110014000070000000000,0,354,132,28,7,0,0,6,354,E01
38402,110014000080000000000,0,1,3,1,0,0,0,0,3,E02
38403,110014000090000000000,0,180,32,30,1,0,0,5,180,E01
38404,110014000100000000000,1,328,38,19,8,0,0,0,328,E01
38405,110014000110000000000,0,179,35,10,1,0,2,0,179,E01

In [9]:
pop_strata.to_csv('../../outputs/01_strata/census_strata_per_block.csv')